spring:
  datasource:
<<<<<<< HEAD
    #    url: ${SPRINGDATASOURCEURL:jdbc:mysql://localhost:3306/rental}
    url: ${SPRINGDATASOURCEURL:jdbc:mysql://mysqldb:3306/rental?useSSL=false}
    username: ${SPRINGDATASOURCEUSERNAME:root}
    password: ${SPRINGDATASOURCEPASSWORD:krs1krs1}
=======
    password: ${SPRINGDATASOURCEPASSWORD:root}
    username: ${SPRINGDATASOURCEUSERNAME:root}
    url: ${SPRINGDATASOURCEURL:jdbc:mysql://mysqldb:3306/rental?useSSL=false}
>>>>>>> 5f2575d0d5855ce6887dc8dfc552127d0f9e177a
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: false
    hibernate:
<<<<<<< HEAD
      ddl-auto: create
=======
      ddl-auto: create-drop
>>>>>>> 5f2575d0d5855ce6887dc8dfc552127d0f9e177a
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
<<<<<<< HEAD

debug: false

=======
  main:
    banner-mode: off

debug: false


jwt.secret: ${CAR_RENTAL_SECRET_KEY:x7D*6]]s#j4ZI{M"V"4+[X%KbTW+Y3GI^KJb+E!n8^<nRbCboV'68m<{H+nGYXJ}
>>>>>>> 5f2575d0d5855ce6887dc8dfc552127d0f9e177a
